server:
  port: 8091

spring:
  application:
    name: netty-client

  kafka:
    bootstrapAddress: kafka:9092
    consumer:
      group-id: testGroup
    topic:
      name: testTopic

netty:
  host: netty-server
  port: 8099
